#pragma once

#include <stdint.h>

#define BOB_LAUNCHER_APP_ID "io.github.trbjo.bob.launcher"
#define BOB_LAUNCHER_OBJECT_PATH "/io/github/trbjo/bob/launcher"

#define MATCH_MAX_LEN 1024
#define MATCH_MAX_LEN_PENALTY -1024

#define SCORE_MAX (int32_t)INT16_MAX
#define SCORE_LOWEST MATCH_MAX_LEN_PENALTY
#define SCORE_MIN MATCH_MAX_LEN_PENALTY

#define SCORE_BELOW_THRESHOLD -1024
#define SCORE_ABOVE_THRESHOLD -1023
#define SCORE_DECREMENT_MINOR 160
#define SCORE_DECREMENT_MEDIUM 100
#define SCORE_DECREMENT_MAJOR 60
#define SCORE_INCREMENT_MINOR 240
#define SCORE_INCREMENT_SMALL 500
#define SCORE_INCREMENT_MEDIUM 700
#define SCORE_INCREMENT_LARGE 900
#define SCORE_INCREMENT_HUGE 1100
#define SCORE_BELOW_AVERAGE 1200
#define SCORE_AVERAGE 1400
#define SCORE_ABOVE_AVERAGE 1600
#define SCORE_GOOD 1800
#define SCORE_VERY_GOOD 2400
#define SCORE_EXCELLENT 3000
#define SCORE_PRETTY_HIGH 6000
#define SCORE_HIGHEST 8191
